import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-BR">
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <header>
                    <nav>
                        <h1>Gazeta</h1>
                        <div>
                            <button>Assinar</button>
                            <button>Entrar</button>
                        </div>
                    </nav>
                </header>

                <main>{children}</main>

                <footer>
                    <div>
                        <p>&copy; 2025 Gazeta do Povo - Teste Técnico</p>
                    </div>
                </footer>
            </body>
        </html>
    );
}
